# roles/docker_setup/tasks/main.yml
---
- name: Install prerequisite packages for Docker
  ansible.builtin.apt:
    name: ['ca-certificates', 'curl']
    state: present
    update_cache: yes

- name: Ensure directory for Docker GPG key exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker's official GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
    force: yes

- name: Ensure Docker GPG key has correct permissions
  ansible.builtin.file:
    path: /etc/apt/keyrings/docker.asc
    mode: 'a+r'

- name: Add the Docker repository to Apt sources
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    filename: docker

- name: Install Docker Engine and plugins
  ansible.builtin.apt:
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io', 'docker-buildx-plugin', 'docker-compose-plugin']
    state: present
    update_cache: yes # Run update after adding the new repo

- name: Ensure Docker service is started and enabled
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes

- name: Add system_user to the docker group
  ansible.builtin.user:
    name: "{{ system_user }}"
    groups: docker
    append: yes
