# playbook.yml
---
- hosts: webservers
  become: yes
  vars_files:
    - group_vars/all/vars.yml
    - group_vars/all/vault.yml

  roles:
    - role: common_base
    - role: docker_setup
    - role: app_deployment
    - role: nginx_setup
    - role: certbot_setup