# roles/common_base/tasks/main.yml
---
- name: Wait for apt-lock to be released
  ansible.builtin.shell: "while lsof /var/lib/dpkg/lock-frontend ; do sleep 10 ; done"
  changed_when: false
  become: true

- name: Update apt cache and install security packages
  ansible.builtin.apt:
    name:
      - ufw
      - fail2ban
    state: present
    update_cache: yes

- name: Set UFW default policies
  community.general.ufw:
    state: enabled
    policy: deny

- name: Allow SSH traffic
  community.general.ufw:
    rule: allow
    port: "{{ ssh_port }}"
    proto: tcp

- name: Allow HTTP and HTTPS traffic
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - "80"
    - "443"

- name: Ensure Fail2ban service is started and enabled
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: yes

- name: Harden SSH configuration
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    backup: yes
  loop:
    - { regexp: '^#?PermitRootLogin', line: 'PermitRootLogin no' }
    - { regexp: '^#?PasswordAuthentication', line: 'PasswordAuthentication no' }
  notify: Restart sshd
