# .github/workflows/ci-cd.yml

name: Java CI/CD Pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the develop branch
  push:
    branches: [ develop ]
  # Triggers the workflow on pull request events but only for the develop branch
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This job runs the build and tests
  build_and_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Step 1: Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up JDK 21 using Temurin distribution and enable Maven caching
      - name: Set up JDK 21
        uses: actions/setup-java@v4 # Use v4 for latest features
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven # Caches dependencies downloaded by Maven

      # Step 3: Grant execute permission for the Maven wrapper script (needed on Linux runners)
      - name: Grant execute permission for mvnw
        run: chmod +x mvnw

      # Step 4: Run Maven clean install (compiles, tests, packages)
      - name: Build and Test with Maven
        # Use Maven wrapper to ensure consistent Maven version
        # 'clean install' compiles, runs tests (surefire), and installs the artifact to local repo
        run: ./mvnw clean install

      # Optional: Upload test reports (useful for debugging failures)
      # This step will run even if the previous steps fail (always())
      - name: Upload Unit Test Reports
        if: always() # Ensures reports are uploaded even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-reports-${{ github.run_id }} # Add run ID for uniqueness
          path: target/surefire-reports/ # Path to Surefire XML reports